=== WingmanD/VideoGamePublishers/WebServer/server/VideoGamePublishersServer/files/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://127.0.0.1/data/schema.json",
  "title": "VideoGamePublisher",
  "description": "A video game publisher",
  "type": "object",
  "properties": {
    "publisherID": {
      "description": "The name of the video game publisher",
      "type": "integer"
    },
    "publisherName": {
      "description": "The name of the video game publisher",
      "type": "string"
    },
    "publisherDateFounded": {
      "description": "The date the video game publisher was founded",
      "type": "date"
    },
    "publisherCountry": {
      "description": "The country the video game publisher origins from",
      "type": "string"
    },
    "publisherDesc": {
      "description": "A short description of the publisher",
      "type": "string"
    },
    "publisherWebsite": {
      "description": "URL of the publishers website",
      "type": "string"
    },
    "publisherDirector": {
      "description": "CEO of the publisher",
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the director",
          "type": "string"
        },
        "surname": {
          "description": "The surname of the director",
          "type": "string"
        }
      }
    },
    "studios": {
      "description": "A list of studios that are owned by the publisher",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the studio",
            "type": "string"
          },
          "dateFounded": {
            "description": "The date the studio was founded",
            "type": "date"
          },
          "country": {
            "description": "The country the studio origins from",
            "type": "string"
          },
          "director": {
            "description": "CEO of the studio",
            "type": "object",
            "properties": {
              "name": {
                "description": "The name of the director",
                "type": "string"
              },
              "surname": {
                "description": "The surname of the director",
                "type": "string"
              }
            }
          },
          "titles": {
            "description": "A list of games that are developed by the studio",
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "description": "The name of the game",
                  "type": "string"
                },
                "releaseDate": {
                  "description": "The date the game was released",
                  "type": "date"
                },
                "genre": {
                  "description": "Genre of the game",
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "required": [ "publisherID", "publisherName", "publisherDateFounded", "publisherCountry", "publisherDesc", "publisherWebsite", "publisherDirector", "studios" ]
}

=== WingmanD/VideoGamePublishers/WebServer/server/VideoGamePublishersServer/files/data.json
[
    {
        "publisherID": 1,
        "publisherName": "Embracer Group",
        "publisherDateFounded": "2011-06-01",
        "publisherCountry": "Sweden",
        "publisherDesc": "Formerly known as Nordic Games Licensing AB and THQ Nordic AB.",
        "publisherWebsite": "https://embracer.com/",
        "publisherDirector": {
            "name": "Lars",
            "surname": "Wingefors"
        },
        "studios": [
            {
                "name": "Coffee Stain Studios",
                "country": "Sweden",
                "dateFounded": "2010-01-01",
                "numDevelopers": 123,
                "director": {
                    "name": "Stefan",
                    "surname": "Hanna"
                },
                "titles": [
                    {
                        "title": "Satisfactory",
                        "releaseDate": "2019-03-19",
                        "genre": "Factory Building Sim"
                    }
                ]
            },
            {
                "name": "Ghost Ship Games",
                "country": "Denmark",
                "dateFounded": "2016-01-01",
                "numDevelopers": 32,
                "director": {
                    "name": "Søren",
                    "surname": "Lundgaard"
                },
                "titles": [
                    {
                        "title": "Deep Rock Galactic",
                        "releaseDate": "2018-02-28",
                        "genre": "CO-OP PvE FPS"
                    }
                ]
            }
        ]
    },
    {
        "publisherID": 16,
        "publisherName": "Sony Interactive Entertainment",
        "publisherDateFounded": "1993-11-16",
        "publisherCountry": "Japan",
        "publisherDesc": "Handles research, development, production and sales of hardware and software for PlayStation consoles.",
        "publisherWebsite": "https://www.sie.com/en/index.html",
        "publisherDirector": {
            "name": "Jim",
            "surname": "Ryan"
        },
        "studios": [
            {
                "name": "Guerrilla Games",
                "country": "Netherlands",
                "dateFounded": "2010-01-01",
                "numDevelopers": 360,
                "director": {
                    "name": "Angie",
                    "surname": "Smets"
                },
                "titles": [
                    {
                        "title": "Horizon Zero Dawn",
                        "releaseDate": "2017-02-28",
                        "genre": "Open World RPG"
                    },
                    {
                        "title": "Horizon Forbidden West",
                        "releaseDate": "2022-02-18",
                        "genre": "Open World RPG"
                    }
                ]
            },
            {
                "name": "Santa Monica Studio",
                "country": "United States",
                "dateFounded": "1999-01-01",
                "numDevelopers": 250,
                "director": {
                    "name": "Yumi",
                    "surname": "Yang"
                },
                "titles": [
                    {
                        "title": "God of War",
                        "releaseDate": "2018-04-20",
                        "genre": "RPG"
                    }
                ]
            }
        ]
    },
    {
        "publisherID": 2,
        "publisherName": "505 Games",
        "publisherDateFounded": "2006-01-01",
        "publisherCountry": "Italy",
        "publisherDesc": "Medium sized publisher based in Milan.",
        "publisherWebsite": "https://505games.com/",
        "publisherDirector": {
            "name": "Neil",
            "surname": "Ralley"
        },
        "studios": [
            {
                "name": "505 Games",
                "country": "Italy",
                "dateFounded": "2006-01-01",
                "numDevelopers": 66,
                "director": {
                    "name": "Neil",
                    "surname": "Ralley"
                },
                "titles": [
                    {
                        "title": "Control",
                        "releaseDate": "2019-08-27",
                        "genre": "Paranormal RPG"
                    }
                ]
            }
        ]
    },
    {
        "publisherID": 3,
        "publisherName": "Xbox Game Studios",
        "publisherDateFounded": "2006-01-01",
        "publisherCountry": "United States",
        "publisherDesc": "Part of Microsoft Gaming division.",
        "publisherWebsite": "https://www.xbox.com/en-US/xbox-game-studios",
        "publisherDirector": {
            "name": "Phil",
            "surname": "Spencer"
        },
        "studios": [
            {
                "name": "343 Industries",
                "country": "United States",
                "dateFounded": "2007-01-01",
                "numDevelopers": 450,
                "director": {
                    "name": "Pierre",
                    "surname": "Hintze"
                },
                "titles": [
                    {
                        "title": "Halo 5",
                        "releaseDate": "2015-10-27",
                        "genre": "FPS"
                    }
                ]
            },
            {
                "name": "Obsidian Entertainment",
                "country": "United States",
                "dateFounded": "2003-06-12",
                "numDevelopers": 200,
                "director": {
                    "name": "Feargus",
                    "surname": "Urquhart"
                },
                "titles": [
                    {
                        "title": "The Outer Worlds",
                        "releaseDate": "2019-10-25",
                        "genre": "Open World RPG"
                    }
                ]
            }
        ]
    },
    {
        "publisherID": 4,
        "publisherName": "Nintendo",
        "publisherDateFounded": "1889-09-23",
        "publisherCountry": "Japan",
        "publisherDesc": "Game developer, publisher and hardware developer.",
        "publisherWebsite": "https://www.nintendo.com/",
        "publisherDirector": {
            "name": "Shuntaro",
            "surname": "Furukawa"
        },
        "studios": [
            {
                "name": "Nintendo Software Technology",
                "country": "United States",
                "dateFounded": "1998-01-01",
                "numDevelopers": 50,
                "director": {
                    "name": "Minoru",
                    "surname": "Arakawa"
                },
                "titles": [
                    {
                        "title": "Super Mario Odyssey",
                        "releaseDate": "2017-10-27",
                        "genre": "Platformer"
                    }
                ]
            }
        ]
    },
    {
        "publisherID": 5,
        "publisherName": "Tencent Games",
        "publisherDateFounded": "2003-01-01",
        "publisherCountry": "China",
        "publisherDesc": "Large publisher focusing on mobile game market.",
        "publisherWebsite": "https://game.qq.com/",
        "publisherDirector": {
            "name": "Mark",
            "surname": "Ren"
        },
        "studios": [
            {
                "name": "Aurora Studio Group",
                "country": "China",
                "dateFounded": "2007-01-01",
                "numDevelopers": 100,
                "director": {
                    "name": "Ethan",
                    "surname": "Yu"
                },
                "titles": [
                    {
                        "title": "Ring of Elysium",
                        "releaseDate": "2018-09-19",
                        "genre": "Battle Royale"
                    }
                ]
            }
        ]
    },
    {
        "publisherID": 6,
        "publisherName": "Team17",
        "publisherDateFounded": "1990-12-07",
        "publisherCountry": "United Kingdom",
        "publisherDesc": "Game developer and publisher created by merger of 17-Bit Software and Team 7.",
        "publisherWebsite": "https://www.team17.com/",
        "publisherDirector": {
            "name": "Debbie",
            "surname": "Bestwick"
        },
        "studios": [
            {
                "name": "Team17",
                "country": "United Kingdom",
                "dateFounded": "1990-12-07",
                "numDevelopers": 200,
                "director": {
                    "name": "Debbie",
                    "surname": "Bestwick"
                },
                "titles": [
                    {
                        "title": "Worms Rumble",
                        "releaseDate": "2020-12-01",
                        "genre": "Arena shooter"
                    }
                ]
            }
        ]
    },
    {
        "publisherID": 7,
        "publisherName": "Devolver Digital",
        "publisherDateFounded": "2009-06-25",
        "publisherCountry": "United States",
        "publisherDesc": "Indie game publisher.",
        "publisherWebsite": "https://www.devolverdigital.com/",
        "publisherDirector": {
            "name": "Douglas",
            "surname": "Morin"
        },
        "studios": [
            {
                "name": "Croteam",
                "country": "Croatia",
                "dateFounded": "2010-01-01",
                "numDevelopers": 38,
                "director": {
                    "name": "Roman",
                    "surname": "Ribarić"
                },
                "titles": [
                    {
                        "title": "Serious Sam: Siberian Mayhem",
                        "releaseDate": "2022-01-25",
                        "genre": "FPS"
                    }
                ]
            }
        ]
    },
    {
        "publisherID": 8,
